name: Lint & Test

# Se ejecuta cuando hay push o PR a main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20] # Ajusta según tu versión de Node

    steps:
      # 1. Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar ESLint
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # 5. Ejecutar tests con Vitest
      - name: Run Vitest
        run: npm run test --reporter=dot
